### ISSUE TITLE
Interface CSP over UART on PIC 24FJ256GA110 with no operating system

### ISSUE THREAD

**Issue by jeremyjallam** [libcsp/libcsp#120]
I am using a PIC 24FJ256GA110 without an operating system. Is there any reference code I can use as a starting point to write the driver for the GOMSpace transceiver?

Also if someone has advice on how to do this it would be greatly appreciated as I am fairly new to the CSP.

**Comment by perwulff** [comment]
hi,
GomSpace has no experiences with running CSP without an OS. We mainly run on 32 bit MCUs with FreeRTOS.
But I think it should be doable by mainly implementing src/arch/* APIs on your platform. There will of course be room for improvements in form of optimisation.

**Comment by carlgonz** [comment]
Hi @jeremyjallam. Not sure if you can use LibCSP without an OS. However, for the SUCHAI I nanosatellite we used the PIC24FJ256GA110 with FreeRTOS and LibCSP. Please check the repo and feel free to use the code if it is useful for you: https://github.com/spel-uchile/SUCHAI

**Comment by johandc** [comment]
CSP is no longer dependent on tasks since the router is now callable from an event loop.

Semaphores and mutexes are not needed when you run OS less.

The only requirement would be queues, which can very easily be implemented using a ring buffer.

So with a little work, CSP will run fine without an os.
