### ISSUE TITLE
Update documentation in develop branch (version 1.6)

### ISSUE THREAD

**Issue by perwulff** [libcsp/libcsp#151]
The documentation is out of date with the latest changes done in develp/version 1.6

**Comment by marcobergamin** [comment]
Hello,

I am currently migrating CSP from v1.5 to v1.6 and I have noticed that my i2c driver is now broken due to the changes in the interfaces (csp_i2c_if.h).

I was wondering if there is a plan to add some documentation about drivers implementation and if somebody could provide a reference implementation of a i2c driver updated to the csp version.

Thank you
Marco Bergamin

**Comment by perwulff** [comment]
hi Marco,
We will update the Wiki pages to libcsp version 1.6, they explains how to implement a driver.
