### ISSUE TITLE
Unify return value and errors

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#209]
As #23 suggested, we should use unified scheme for error numbers and return values.  We have `CSP_ERROR_NONE` defined as `0` in `csp_error.h` but `csp_queue`, `csp_semaphore`, and `csp_mutex` uses `1`, or `pdTRUE` / `pdPASS` as OK.

Because this is API breaking changes, it should only be for 2.0, as #23 suggested.

I'm creating this new issue becuase #23 is already closed.

**Comment by johandc** [comment]
This will have to wait until a 2.1 or subsequent release. Since 2.0 is already in release candidate.

Theres a lot of cleanup that I would like to perform if I had the change to do over. 😊

**Comment by yashi** [comment]
I didn't know 2.0 is that close.  There is no RC tag yet, right?

Would you give v2.1, or v3.0, tag to this?  Or did you mean we won't fix this?  I'm sure it's a huge change.

**Comment by johandc** [comment]
I think we want to go with zero as OK and negative values as error.

This means the change needs to be in csp/arch which is used much more seldom than csp io. But yes it IS somewhat of a bigger change.

I don't want to ignore it, because it IS an inconvenient inconsistency. So I would like to address some of these internal stuff in a major release. 

The next API break will be in 2.1

**Comment by johandc** [comment]
I fixed the csp_send return value issue now

**Comment by johandc** [comment]
csp_mutex is gone now too

**Comment by johandc** [comment]
The CSP_QUEUE_OK changed was non breaking, since only the macros was used it was only a matter of changing the value, and fixing the return of the FreeRTOS queue functions.
