### ISSUE TITLE
memset() in csp_conn_free_resources()

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#220]
This is more of a question rather than a bug report.

In `csp_conn_free_resources()`, we `memset()` both `conn_lock` and `sport_lock` without calling `csp_bin_sem_remove()`.  What is the rational behind this?

https://github.com/libcsp/libcsp/blob/fe8b2283331cc33e5b6a3b276afadd7ca6defcf7/src/csp_conn.c#L133-L137

**Comment by johandc** [comment]
Good question...

It was added by per wulf here 
https://github.com/libcsp/libcsp/commit/11906eab97e6b4ab92409b41bd85de9286ef4da6

Seems like a bug to me.

I had an idea to use the queue system for buffer pools instead of arrays with a linear search. This would take it from O(n) to O(1) and also take care of locking. 

I believe this is already how the buffer pool is working.

Also the sport lock could be replaced by compiler based atomics.

**Comment by johandc** [comment]
csp_conn_free_ressources have been removed now that we don't use any dynamic memory. Problem Fixed :)
