### ISSUE TITLE
Simplify assert and stdout from library

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#221]
It seems to me that the current code have mixed debugging feature and logging feature.  i.e) In order to print error log with `csp_log_error()`, we must enable `CSP_DEBUG`.  The function to set log level is called `csp_debug_set_level()`, instead of `csp_log_set_level()`.  It might be a good idea to separate them.

Actually, it'd be just a bunch of renames to do `s/csp_debug_/csp_log_/ig`.  We only have `csp_assert()` for debugging.

**Comment by johandc** [comment]
So if I understand you correctly, you want to have CSP_DEBUG just control the CSP_ASSERT, and rename debug_set_level to log_set_level?

Your point about the confusion is valid. But i think i have a better idea for the solution.
It's been a while since this systems was made, and if I should make it again I would do the following:

1. Use native assert.h I don't know why this should have ever been it's own function. Maybe for portability. But i have yet to find one that didn't have assert.h

2. Delete the entire log system. This is filled with nasty macros and just a right mess :)

3. Introduce a set of variables corresponding to each of the 7 so-called log levels we have today. I believe we already have the state of the debugging stored in a uint8_t array. However, this is quite limiting, and it's not easy to make a new debug "level" for lets say a new interface file under test or whatever.

4. Management of runtime variables. We have a few (RDP options, and these log levels) should be handled with a convenient helper function, but the variables themselves should be exported though a header file too. This is important because, it is not CSP's task to handle configuration management. And for users who already have a system for that (see https://github.com/spaceinventor/libparam) it is much easier when the parameters are just exported for memory mapping.

5. Everywhere logging is needed, instead of calling csp_log_error("some text") i would do the following:

```
if (csp_log_error) { printf("some text"); }

or

if (csp_log_error) {
    printf("some text");
}
```

It takes up slightly more room, but the code is readable and macro free. Much simpler to actually understand what happens. it also opens up to actual log levels. So the variable csp_log_error, could take multiple values, not just 0 or 1. For example when i'm writing drivers today, each individual driver / module or subsystem of the code has its own uint8_t log or debug parameter. This opens up for much much finer grained debugging. The other advantage is that when writing the driver i just declare my own log/debug parameter in my own local scope, meaning that its ultra simple and allows for infinite expansion, without a centralised log og debugging system.

**Comment by yashi** [comment]
> Use native assert.h

You mean, `<assert.h>` from C standard library?  I'm all for it.

> Delete the entire log system.

hmm... I'm not sure.  More on later.

> Introduce a set of variables corresponding to each of the 7 so-called log levels we have today.

I think introducing a variable for log level is fine.  But I don't think we need multiple variables for log _levels_ though.

Instead, we should, if we want to, distinguish levels with categories.  Having runtime variables corresponding categories such as "buffer", "packet", "protocol", "lock", or any thing we'll add, will be nice.   For levels, if you set to a certain level, you will see all higher level as well.  For category, you see what you set.  This idea will not simplify the logging system, though.

> Management of runtime variables

Nice :+1: 

> `if (csp_log_error) { printf("some text"); }`

It's OK as long as it's just an implementation of logging function.  I want to use an external logging feature, like the one provided by an underlying OS.  And I'd like to control the runtime log level through the OS.   If this is an API, you can't delegate to a underlying OS or platform.  What the platform get is a plain `printf()` without a severity level.  The platform has no clue about the message at all.

**Comment by johandc** [comment]
Okay yes we agree on the categories. This is what I meant with separate variables. One for each category. Like packet, drivers router and so on.

However I believe each category should be free to define its own levels, or bitfields (sub category). Like the error bit could be set simultaneously with a TX or RX bit or whatever flag that particular debug like will provide. As long as any bit is matched, it will produce an output.

So we can encourage the last four bits to always remain the same we have today. Err, warn, info, debug. And have the other fields in each category be free to choose from.

The call itself can be macroed or as a function call. To allow for external logging systems. However most systems should implement a way to catch stdout anyways.

We are moving more towards error counters, and we should be better to use them. Maybe together with logging for convenience.

**Comment by johandc** [comment]
It's actually a problem with assert.h, because it uses __FILE__ which is considered harmful for reproducible builds. Because it contains the build folder. So one example could be if one developer builds his firmware in a short path /home/johan/git/proj, and another one has a longer name like /home/myverylongusername/git/mylongprojectname if you take this differece and multiply that with the numer of asserts in the code. The software image now does not fit the device. Changing the memory footprint and so on...

**Comment by yashi** [comment]
https://github.com/libcsp/libcsp/blob/5344d8d00b55ed8674f2bd32083fc1844b29acdc/include/csp/csp_debug.h#L81

One advantage of `csp_assert()` is that it has a hook, `csp_assert_fail_action()`.  I assume we don't have it with standard `assert()`.  But, a simple question, you don't want to use `assert()` in the FM / Release build, do you?

**Comment by johandc** [comment]
That's a tricky question.

I want reproducible builds, and i want to fly what i test. So YES, i want to fly the single "debug build". I just want it to fail nicely. So ideally each assert should be replaced with runtime recoverable faults, instead of the current action which is to crash the system. Even worse would be to run a build without debugging, and then just continue, potentially making more harm than a crash.

Another point is that `csp_assert_fail_action()` is rather useless, because i think it's individual which action should be made when an error is encountered. Sometimes you need to free some resources and return a known value. The issue with assert() is that it leaves the system in an unusable state.

The only advantage to assert is that it can be used to gain higher performance, by running rigorous testing in advance, and then removing all the error checking in a production release. However, this is NOT the philosophy i want to take. I want the code to be capable of detecting errors, and handle it gracefully. Even though it costs some performance to make the checks into runtime checks.

One method that we commonly use, is to have error counters being incremented, to let the operator aware that there is a code problem. I think the majority of the flash taken by the CSP library, actually consists of extremely verbose error messages. Many which could be replaced with simple counters or flags, raising the attention of the developer. After which, he could enable verbose debugging to include the printfs to stdout.

**Comment by yashi** [comment]
> I want the code to be capable of detecting errors, and handle it gracefully.

I totally agree.  We want that in our flight software.  And the standard assert, or the mentality around assert isn't aligned to what we want.  This has been causing impedance mismatch in many projects.  Thus, my question: We do _not_ want to use the standard `assert()` because it doesn't do what we want.

> One method that we commonly use, is to have error counters being incremented

Yes, I'm aware of that.
And that is not CSP's job, IMHO.  Because it's nothing to do with network protocol.

I'd rather want libcsp to pass logging and error handing, or any other network protocol unrelated issues for that matter, down to the underlying OS or encapsulating framework.  To do that, I want libcsp to wrap as little arch specific functions as it needs, call them via wrapper in libcsp code base.

But this is a totally opposite direction if you want libcsp to be _the_ cubesat framework.

I guess my question boils down to: "Where do you want libcsp to be?"  This is a question I wanted to ask you for quite a while. It doesn't related to the assert issue but it'd be nice if you can give us some future direction you have.

BTW, in Zephyr, we have a plug-able logging framework; we can write a backend to do the error counting and reporting on our required request timing.

**Comment by johandc** [comment]
Okay, we agree thus far. Just one comment regarding the error counters. I think I do want to include the storage for those in the library. with the option of exporting them for mapping into users parameter system of choice. I will add a contrib file containing parameter mappings for our libparam. If zephyr has anything similar that could go in there too.
