### ISSUE TITLE
Python transaction binding not allowing "allow_any_incoming_length" argument

### ISSUE THREAD

**Issue by skoold2003** [libcsp/libcsp#344]
When setting the allow_any_incoming_length argument to True on the libcsp.transaction method it returns the error "function takes exactly 6 arguments (7 given)"

**Comment by moonlight83340** [comment]
I tested the python binding example few days ago with the current develop branch(https://github.com/libcsp/libcsp/commit/f21c1aa923303c02b9f788c7b6286bc8219c37cb) and the error is not present. 
I'm not sure yet for the libcsp-2-0 because with this branch build with python binding fail. (I will investigate more on libcp-2-0 branch)

Edit (22/08/2024): PR https://github.com/libcsp/libcsp/pull/665 fixes the problem.
The libcsp-2-0 branch now builds correctly, and the error mentioned in the issue no longer occurs.

I believe we can close the issue since both the libcsp-2-0 branch and develop branch are now free of this error.

**Comment by yashi** [comment]
I'm closing this.  @skoold2003 if you still have problems, please reopen it.
