### ISSUE TITLE
Increase the address space

### ISSUE THREAD

**Issue by johandc** [libcsp/libcsp#41]
We have started meeting the limitations to the CSP 1.0 header. I would like to start a discussion about where to go with version 2.0, and would like to start with some requirements:

1) CSP 2.0 should be backwards compatible with CSP 1.0: This means that a CSP 1.0 message must be valid on any 2.0 node, and a 2.0 message should be valid on a 1.x node. I don't know if this can be fixed somehow using the existing code, but we should at least start now by adding a version field to the reserved bits and ensure that CSP from version 1.3 (when it's released) is capable of distinguishing between packet formats.
2) CSP 2.0 should have a larger address space allowing for inter satellite networks, and maybe even a possible ground network extension (attaching a satellite ID or similar). Maybe we can take a look at the CCSDS recommendations for IPv4 in satellites, i don't know if there is some inspiration or not.

**Comment by perwulff** [comment]
In order to simplify things, would it be possible to force all apps within a satellite to switch to version 2.0, i.e. it is not possible to mix apps using CSP 1.x and 2.x within a satellite? The mapping between 1.x and 2.x would be done in the radio apps (satellite to satellite) or on ground, if the satellite only communicates with ground stations. In worst case, it may require a handshake between receiver and transmitter - but it will reduce code and complexity in all nodes in the satellite, because nodes only need to understand a single CSP version.
Perhaps CSP in the future will only be used inside the satellite, since communication is moving towards IP.

**Comment by johandc** [comment]
#161 Fixes this
