### ISSUE TITLE
Custom endpoints in ZMQ-Hub interface

### ISSUE THREAD

**Issue by pacheco017** [libcsp/libcsp#56]
Hi! First of all, I want to thank you for this wonderful project! It has really fitted my needs and I would be very happy if I can give you back some improvements.

I would like to introduce some changes in the ZMQ-Hub interface, to allow for more flexibility, so I'll need some guidance from you. Based on your feedback, I'll send you a PR with the changes.

For starters, I think it would be better to pass the two full endpoints to `csp_zmqhub_init` (both publisher and subscriber), instead of just the `host`. This would allow to use any zmq supported transport (eg. IPC), instead of just TCP, and remove hardcoded ports (6000, 7000).

By the way, is there any reason this interface outputs various errors using `printf` directly? Wouldn't it be better to use csp log functions instead? If not, would you consider at least sending output to stderr?

Thanks for your time!

**Comment by johandc** [comment]
Hi,

I think it's a good idea to allow custom endpoints. However i would still like to maintain the old csp_zmqhub_init call for "default options" used by our systems.

So i suggest that you add a second function called
csp_zmqhub_init_w_endpoints() or similar name you find suiting.

Then you can change the implementation of csp_zmqhub_init to call csp_zmqhub_init_w_endpoints once it has setup the default endpoints on TCP.

And yes, we should of course use csp_debug instead of printf.
