### ISSUE TITLE
Add __version__, __model__, __date__, __time__ to uptime

### ISSUE THREAD

**Issue by johandc** [libcsp/libcsp#6]
Add some string's to uptime response. Should support dynamic length strings. such as
# define **VERSION** "42ab3257" // Git identifier
# define **MODEL** "NanoCom U482C"

**date** and **time** should come from the compiler already.

**Comment by jledet** [comment]
I have started working on a 'CSP Management Protocol' on port 0 for this kind of information. Ideally, we should move all the services to port 0, but that won't be possible in the near future due to backward compatibility requirements. 

Other CMP messages could be used to change routes in flight (if you e.g. have redundant/different radios), querying for interface status, configuring interfaces, etc.

**Comment by jledet** [comment]
Hostname and model can now be set using `csp_set_hostname()` and `csp_set_model`. The values can be read using `csp_cmp_ident()`.
