### ISSUE TITLE
buffer overflow

### ISSUE THREAD

**Issue by dimitrovand** [libcsp/libcsp#627]
The issue lies in `csp_transaction_persistent` and `csp_ping`, identical to the one described here: https://github.com/libcsp/libcsp/pull/503. I believe `csp_buffer_get()/csp_buffer_get_isr()` should be deprecated (at least with __attribute__((deprecated))) to prevent similar issues in the future. I would suggest that the current usages of `csp_buffer_get()/csp_buffer_get_isr()` be examined carefully.

**Comment by moonlight83340** [comment]
I think it would be a good idea to mark the function parameter deprecated since we don't use it anymore in libcsp.
I was previously thinking of removing the current value pass to `csp_buffer_get()/csp_buffer_get_isr()` in libcsp to make all of them to 0 😅 
We could also define something like CSP_UNUSED_INT_PARAMETER. To make sure user understand that the parameter isn't used in the function...
