### ISSUE TITLE
Add zmqhub service

### ISSUE THREAD

**Issue by jledet** [libcsp/libcsp#68]
The csp_if_zmqhub interface isn't of much use without the matching zmqhub service. Clean it up and push it to the public tree.

**Comment by niklas88** [comment]
In the meantime I found a minimal zmqhub is just a [few lines of C](https://gist.github.com/niklas88/e67a19e8171cf2ad1b79df5ac34f808c)
Compile with `gcc -O2 -lzmq -o minzmqhub minzmqhub.c` and run with `./minzmqhub 'tcp://*:7000' 'tcp://*:6000'` . However I've found that port 6000 is a default port used by X.org so I'm actually using 6111 and 7111. This sends all messages to everyone including the originating node but since nodes filter what's meant for them this shouldn't be too problematic.

**Comment by perwulff** [comment]
The zmqproxy exists in the example folder and works well with the C/Python examples (develop branch)
