### ISSUE TITLE
Increase MTU on packets and add fragmentation on layer 3

### ISSUE THREAD

**Issue by johandc** [libcsp/libcsp#7]
Original idea: Implement full support for data buffering and fragmentation. (TCP-a-like)

Proposed change: Increase MTU and provide automatic fragmentation on layer 3. (unless the DF flag is set). This leads to two new fields in the routing table. These fields may be set statically in the table compile time, or discovered by a traceroute.

1) Max MTU
2) Estimated round trip time.

**Comment by jledet** [comment]
I think we should keep the message-oriented approach, and instead work on increasing the CSP MTU to 64k and implement a common fragmentation mechanism. Maybe SCTP has some points for inspiration.

This requires a rewrite of the buffer system, since most systems cannot allocate multiple full 64k buffers. Either we have to use malloc, which is a problem with ISRs and DMA, or we somehow have to 'bundle' multiple buffer elements.

**Comment by johandc** [comment]
Yes. There is no need for byte-oriented streams like TCP provides. Maybe large file transfers could benefit from this, but i see no reason why the FTP application should rely on this. The current datagram approach works well also in situations where TCP would fail due to bad SNR.

I'm renaming this issue.

**Comment by jledet** [comment]
We could still make some helper function to transfer enumerated packets from a large buffer, both with or without RDP.

**Comment by johandc** [comment]
Yes. Maybe time to dig out that old "fc_chunk.c" file again :)

**Comment by jledet** [comment]
This is solved with SFP.
